name: Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:

  build-upload:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
    - name: Set PHP version
      run: sudo update-alternatives --set php /usr/bin/php7.4
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup variables
      id: vars
      run: |
        echo "::set-output name=yarn-cache-path::$(yarn cache dir)"
        echo "::set-output name=composer-cache-path::$(composer config cache-files-dir)"
    - name: Cache Composer
      uses: actions/cache@v1
      with:
        path: ${{ steps.vars.outputs.composer-cache-path }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Cache Yarn
      uses: actions/cache@v1
      with:
        path: ${{ steps.vars.outputs.yarn-cache-path }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-
    - name: Install Composer dependencies
      run: composer install -o --no-progress --no-dev
    - name: Install Node dependencies
      run: yarn install --no-progress
    - name: Build assets
      run: yarn build
    - name: Ignore local changes
      run: git checkout -- .
    - name: Upload files
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      with:
        flags: '-aCh'
        options: '--stats --delete-after --exclude-from=".deploy-excludes"'
        src: '.'
        dest: ${{ secrets.STAGING_RSYNC_URL }}
