name: Test

on: push

env:
  PHP_VERSION: "8.2"
  NODE_VERSION: 23

jobs:
  syntax:
    name: PHP Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
      - name: Lint
        run: composer syntax
  phpcompat:
    name: PHP Compat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
      - name: Analyze
        run: composer phpcompat
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
      - name: Analyze
        run: composer phpstan
  phpcs:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
      - name: Coding Standards
        run: composer phpcs
  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Corepack
        run: corepack enable
      - name: Set Yarn version
        run: corepack prepare yarn@stable --activate
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install Node dependencies
        run: yarn install
      - name: Lint SCSS files
        run: yarn lint:scss
  eslint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Corepack
        run: corepack enable
      - name: Set Yarn version
        run: corepack prepare yarn@stable --activate
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install Node dependencies
        run: yarn install
      - name: Lint JS files
        run: yarn lint:js
  tsc:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Corepack
        run: corepack enable
      - name: Set Yarn version
        run: corepack prepare yarn@stable --activate
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install Node dependencies
        run: yarn install
      - name: Check types
        run: yarn tsc
