name: Test

on: push

jobs:
  syntax:
    name: PHP Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Set PHP version
        run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP Dependencies
        uses: "ramsey/composer-install@v2"
      - name: Lint
        run: composer syntax
  phpcompat:
    name: PHP Compat
    runs-on: ubuntu-latest
    steps:
      - name: Set PHP version
        run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP Dependencies
        uses: "ramsey/composer-install@v2"
      - name: Analyze
        run: composer phpcompat
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Set PHP version
        run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP Dependencies
        uses: "ramsey/composer-install@v2"
      - name: Analyze
        run: composer phpstan
  phpcs:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Set PHP version
        run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP Dependencies
        uses: "ramsey/composer-install@v2"
      - name: Coding Standards
        run: composer phpcs
